# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: py37_test
        image: python:3.7
        script: # Modify the commands below to build your repository.
          - pip install .
          - pip install pytest
          - python setup.py test
    - step:
        name: py36_test
        image: python:3.6
        script: # Modify the commands below to build your repository.
          - pip install .
          - pip install pytest
          - python setup.py test
